### ISSUE TITLE
Can't edit files with Font Awesome characters

### ISSUE THREAD

**Issue by nraygun** [gphalkes/tilde#36]
When reporting a bug, please provide the information requested below to aid in the diagnosis of the problem. For feature requests you can remove the template text.

What OS are you using (including version): Ubuntu 18.04 with i3
What terminal were you running Tilde on when you ran into the issue: xfce4-terminal version 0.8.7.4

Please paste the result of running 'tilde --version':
Tilde version 0.4.0
Copyright (c) 2011-2018 G.P. Halkes
Tilde is licensed under the GNU General Public License version 3
Library versions:
  libt3config 0.2.11
  libt3highlight 0.4.5
  libt3key (through libt3widget) 0.2.8
  libt3widget 0.6.2
  libt3window 0.3.0
  libtranscript 0.3.3
  libunistring 9.9.?

Please describe the problem. If possible, include the action you performed, the expected result and the actual result in the description.
Opening the attached file results in a dialog that says "Conversion from encoding UTF-8 is irreversible Continue Abort"
Choosing either results in a text file that is not the original.
Tried various options with the "-e" parameter.
[test.txt](https://github.com/gphalkes/tilde/files/2591316/test.txt)

**Comment by gphalkes** [comment]
Thanks for reporting the bug. I had already seen your conversation on the IRC channel, and the bug should be fixed in commit aadbf2b1f5378db83d435c173d72bb5ffdba7967. This will be part of the next release.

For more details on the problem: Font Awesome uses the so-called Private Use Area of Unicode to represent (some of) its characters. Tilde assumed that these were unusable, and thus converted them to the Replacement Character (and notified you that it did so, to make sure you are aware of the problem). However, instead of assuming that Private Use Area characters are invalid, it should simply leave them as is. This is what the fix does.

**Comment by nraygun** [comment]
Outstanding!
Thanks for the quick response.
Tilde is fantastic.

-Manny

**Comment by nraygun** [comment]
I'm not really familiar with git and such.
How will I know when the new release is available?
Hoping to just do a "sudo apt install tilde" at some point.

Ho, Ho, Ho,

Manny

**Comment by gphalkes** [comment]
The tilde releases 0.4.3 and 1.0.0 have the fixes included. If you are getting your packages from the Tilde repositories, you should have it already. Otherwise, you will have to wait until the next release of your distribution (Ubuntu 19.04 and Debian buster will have version 1.0.0).

**Comment by nraygun** [comment]
I ran this as your site suggests, but I still get an old version:
wget http://os.ghalkes.nl/sources.list.d/install_repo.sh ; sudo sh
./install_repo.sh ; sudo apt-get install tilde

$ tilde -V
Tilde version 0.4.0
Copyright (c) 2011-2018 G.P. Halkes
Tilde is licensed under the GNU General Public License version 3
Library versions:
  libt3config 0.2.11
  libt3highlight 0.4.5
  libt3key (through libt3widget) 0.2.8
  libt3widget 0.6.2
  libt3window 0.3.0
  libtranscript 0.3.3
  libunistring 9.9.?

I also noticed an error. Something about a public key not available:
W: GPG error:
http://download.opensuse.org/repositories/home:/gphalkes:/tilde/xUbuntu_18.04
./ Release: The following signatures couldn't be verified because the
public key is not available: NO_PUBKEY 20BEECE5E0B20CEA
E: The repository '
http://download.opensuse.org/repositories/home:/gphalkes:/tilde/xUbuntu_18.04
./ Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore
disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration
details.

I ran the part that I think is the problem (adding a "keyring") and I get
this:
$ sudo apt-get --allow-unauthenticated install tilde-keyring
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package tilde-keyring

Suggestions?

**Comment by gphalkes** [comment]
Thanks for letting me know. As it turns out, I did something wrong with enabling the tilde-keyring package for the repository. Running the script again should resolve the problem now.

**Comment by nraygun** [comment]
Still no go. I think this is the relevant area that's causing the problem.
W: GPG error:
http://download.opensuse.org/repositories/home:/gphalkes:/tilde/xUbuntu_18.04
./ Release: The following signatures couldn't be verified because the
public key is not available: NO_PUBKEY 20BEECE5E0B20CEA
E: The repository '
http://download.opensuse.org/repositories/home:/gphalkes:/tilde/xUbuntu_18.04
./ Release' is not signed.

**Comment by gphalkes** [comment]
Not sure what the reason for this is. However, the simplest way to resolve is to download the tilde-keyring package manually from http://download.opensuse.org/repositories/home:/gphalkes:/tilde/xUbuntu_18.04/all/tilde-keyring_2017.04.16-1_all.deb and use dpkg -i tilde-keyring_2017.04.16-1_all.deb to install it. After that, an apt-get update and apt-get upgrade should do the trick.

**Comment by nraygun** [comment]
Woohoo! That worked! Thank you so much!

Should tilde display the actual character from Font Awesome? Right now, for
each Font Awesome glyph, I get a underlined period.

**Comment by gphalkes** [comment]
This is expected behavior. I'm not fully decided on how to handle this. I first need to check how different terminal emulators handle these characters. 

The problem is that these characters are not defined by the Unicode standard, so it is very hard for Tilde to know if the terminal can render them properly, and what width they will have if they are rendered. It is very likely that there will not be a reasonable way to do this. Programs running under terminal emulators are unfortunately very limited in their possibilities.

**Comment by nraygun** [comment]
Roger that.
FWIW, nano seems to handle these characters for the most part. There are
some that are not rendered properly, but most in my i3 configs are shown as
the glyphs.

Thanks again for all your help.

I hope you and your family have a happy holiday season!

-Manny
